# 服务端口
server:
  port: 80
#开发环境数据库
spring:
  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://82.157.174.105:3306/ygddeveloping?serverTimezone=GMT%2B8
    username: root
